### PR TITLE
(SIMP-2482) Restored ability to build from existing tarball

### PR DESCRIPTION
**Pull request by nick-markowski**
SIMP-2482 #close

### CODE REVIEW

**Comment by jeefberkey** [comment]
Does this also fix `rake clean` and other tasks?

**Comment by nick-markowski** [comment]
@jeefberkey in what way was rake clean broken? I ran it and it looks janky, but things appear to be cleaned up

**Comment by jeefberkey** [comment]
https://simp-project.atlassian.net/browse/SIMP-2716 and personal the same error when running a lot of the component tasks that make up build:auto, like tar.

**Comment by nick-markowski** [comment]
@jeefberkey Clean did not err out as that ticket describes. Thanks for the input, i'll take a look into it.

**Comment by nick-markowski** [comment]
@jeefberkey ran rake clean without these updates with similar (functional) results. I will address rake clean separately; I would review this PR only in the scope of the ticket, building from tarball.

**Pull request merged**
